# ====================== APPLICATION ======================
spring.application.name=SmartLogi_Delivery
server.port=8080

# ====================== DATABASE ======================
spring.datasource.url=jdbc:postgresql://localhost:5432/SmartLogi_Delivery_db
spring.datasource.username=postgres
spring.datasource.password=latifi-2001
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none

spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.yaml

# ====================== LOGGING ======================
logging.level.com.smart_delivery_management.smartlogi_delivery=DEBUG
logging.level.org.hibernate.SQL=DEBUG

# ====================== GOOGLE OAUTH2 ======================
spring.security.oauth2.client.registration.google.client-id= 979200036258-eqol0jfk7b3ljvuk5no54msfjr2peurn.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=openid,email,profile
spring.security.oauth2.client.registration.google.redirect-uri=http://localhost:8080/login/oauth2/code/google

# ====================== JWT CONFIG ======================
# (optionnel) si tu veux ajouter des configs pour le JWT
# jwt.secret=SECRET_KEY_123456_SECRET_KEY_123456
# jwt.expiration=86400000

# ===============================
# OAuth2 - GITHUB
# ===============================
spring.security.oauth2.client.registration.github.client-id=Ov23licp246U6dcSdHUz
spring.security.oauth2.client.registration.github.client-secret=219aed806ba942f9bab9831d1d9575950bfe3431
spring.security.oauth2.client.registration.github.scope=user:email
